title: Workflows Community of Practice
logo: logos/workflows/Full_WICoP.png
description: The Workflows Community of Practice webpage
baseurl: /
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
collections:
  events:
    output: true